### PR TITLE
Add prefer not to answer options where missing; update contributor name

### PR DESCRIPTION
**Pull request by 0xreid**
This PR adds a "Prefer not to answer" option where it was previously missing across multiple answer options.

I also updated my contributor name since I've changed my name since my first contribution to this project.

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks @0xreid. Regarding the contributor name change, why is there such a change? Is this you in the current version and you are looking to update your name? 

Thanks for the updates to the questions!

**Comment by 0xreid** [comment]
> Thanks @0xreid. Regarding the contributor name change, why is there such a change? Is this you in the current version and you are looking to update your name?

I changed my name since my first contribution, including changing my github username (same account, just changed the name), so wanted the contributors file to reflect the new/correct name for me.

**Comment by germonprez** [comment]
got it! Thanks.

**Comment by germonprez** [comment]
Thanks for the PR updating the files @0xreid. We really appreciate it!

**Pull request merged**
