### PR TITLE
Gender identities

### PR DESCRIPTION
**Pull request by sagesharp**
Refactor and expand on the gender identities. This is a long list, but it's important to move gender identity beyond binary genders. All terms are from an LGBTQ community peer-reviewed book by Ashley Mardell, which is cited.

### CODE REVIEW

**Comment by drnikko** [comment]
This looks great!  Thank you very much for getting involved.  
Would love to get a third set of eyes on this - inviting Emma to take a look. 

Do you have thoughts on organizations that don't want to offer all of those identities? Companies that want to do a short questionnaire for their users.

**Comment by sagesharp** [comment]
Gender is a complex subject and we shouldn't erase people's gender identities by trying to shorten a form. Companies are welcome to group people's responses into whatever smaller categories they like, but they shouldn't limit the options.

**Comment by drnikko** [comment]
I 100% agree that we shouldn't erase people's gender identities by trying to shorten a form - gender identity is important!  I'm thinking of communities that  - for any number of reasons - don't want to use the list but _do_ want to ask a gender question.  If we only have one way to ask, I worry that it will be tempting for them to just skip gender entirely, and perhaps that is the recommendation.  But part of the goal of the project is to make so communities aren't forced to do this grouping on their own.  Thinking about having good data from community to community, how can we support communities who have the whole list, and communities who "need" an abbreviated list?

**Comment by drnikko** [comment]
I'm sorry if that wasn't clear.  I'm also _not_ trying to bikeshed this.  Happy to merge and open a separate issue for a short version of the same question.  I think that's a better idea. 

Thank you again for contributing! <3 <3 <3

**Comment by drnikko** [comment]
Actually @sarahsharp can you add yourself to contributors and then I'll merge? (unless you would rather not be there)

**Comment by emmairwin** [comment]
@sarahsharp  these are great. Side-question,  one from the summit, was that maintainers (orgs etc) had little to no understanding of even what non-binary is . 
How can we use this as a learning tool as well for orgs as they implement.   I know that some institutions (thinking higher education  in this one) are afraid of what they don't know, and so will shy away from using a standard like this one.

**Comment by sagesharp** [comment]
All of the information communities want to collect will need to be long in order to be inclusive. For example, I expect the forms for race to get just as long in order to not be U.S. centric. Universities will also push back from using a more inclusive standard because it doesn't fit with U.S. census data. The point of this project should be to promote a more inclusive standard, not settle for the status quo.

If a community doesn't feel they can offer an inclusive list of terms, they shouldn't ask the question. It's the same reason that non-binary people get very upset at gender forms that say "Male/Female/Other". By shorting the list, we risk othering people, so it's better not to ask for shortened versions.

**Comment by emmairwin** [comment]
So, more what I mean is - this IS an opportunity to help people learn.  How might we do that?   For example the person in our session who asked about non-binary clearly just wanted to understand so he could ask better questions.     'Embedded learning/Embedded Empathy'

**Comment by emmairwin** [comment]
" I expect the forms for race to get just as long in order to not be U.S. centric"

- Also in some regions asking for race is illegal.  As another attribute to consider.

**Comment by sagesharp** [comment]
It's possible we could provide links to definitions of various terms. I'm not sure where the definitive resource for those terms should be.

**Pull request merged**
